### ISSUE TITLE
GetLatestWatcherMetrics did not return proper error

### ISSUE THREAD

**Issue by wangchen615** [paypal/load-watcher#27]
GetLatestWatcherMetrics can return nil, nil in case of e.g. HTTP error code 403. (https://github.com/paypal/load-watcher/blob/6c7e96e582364641e5015a7c455327701dbd85f0/pkg/watcher/api/client.go#L107)
Why GetLatestWatcherMetrics return nil, nil instead of just returning a proper error in this case?

@zorro786

**Comment by zorro786** [comment]
@wangchen615 Looks like a bug, should return err there.
