### ISSUE TITLE
Bump dep version for "github.com/prometheus/common"

### ISSUE THREAD

**Issue by Huang-Wei** [paypal/load-watcher#39]
The code below

https://github.com/paypal/load-watcher/blob/1c92ae3f9346943cb3694e7de24c95f851508b61/pkg/watcher/internal/metricsprovider/prometheus.go#L66

is no longer valid in the latest [Prometheus library](https://github.com/prometheus/common/blob/main/config/http_config.go).

The code should be refactored to:

```go
config.NewAuthorizationCredentialsRoundTripper("Bearer", token, rt)
```

This is found when I wanted to bump the version of scheduler-plugins to k8s 1.22.

**Comment by zorro786** [comment]
@wangchen615 Could you please look into upgrading Prometheus library to v0.26.0 from v0.15.0?

**Comment by Huang-Wei** [comment]
@zorro786 I just raised a PR :)
